wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1675097501.822711
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.13
      5: 0.13.7
      8:
      - 1
      - 2
      - 3
      - 5
architecture:
  desc: null
  value: Siamese Network
dataset:
  desc: null
  value: Iceberg
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.01
